engines:
    rubocop:
        enabled: true
    eslint:
        enabled: true
    csslint:
        enabled: true
    bundler-audit:
        enabled: true

ratings:
    paths:
        - "lib/*.php"
        - "modules/*/*.php"
        - "modules/*/*.js"
        - "modules/*/*.css"

exclude_paths:
    - "modules/*"
    - "tests/*"
    - "third_party/*"
    - "docs/*"
    - "language/*"
    - "website/*"
