engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  bundler-audit:
    enabled: true

exclude_paths:
 - "test/*"
 - "third_party/*"
 - "docs/*"
 - "language/*"
 - "modules/*/assets/*"
